image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      nvm install
      npm i -g nx commitizen
      npm i

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

github:
  prebuilds:
    addComment: true
    branches: true

vscode:
  extensions:
    - 'esbenp.prettier-vscode'
    - 'firsttris.vscode-jest-runner'
    - '42crunch.vscode-openapi'
    - 'redhat.vscode-yaml'
    - 'dbaeumer.vscode-eslint'
