# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: npm install
        run: npm install

      - name: Test affected
        # You may pin to the exact commit or the version.
        # uses: MansaGroup/nrwl-nx-action@0bd602b44260ea0a634b26dc6e224285769c8937
        uses: MansaGroup/nrwl-nx-action@v1.0.1
        with:
          # Comma-separated list of targets to execute
          targets: test, e2e
          # Comma-separated list of projects to use
          # projects: 
          # Run the targets on all projects
          # all: # optional, default is false
          # Use the Nx' affected subcommand to only process affected projects
          # affected: # optional, default is true
          # Run the tasks in parallel (can be expensive)
          # parallel: # optional, default is false
          # Optional arguments to append to the Nx command
          # args: # optional, default is 
